### PR TITLE
look for other linked resources (css, script, ajax call on page load)

### PR DESCRIPTION
**Pull request by doxakis**
Hi,
I added extra checks for linked resources (css, external script, font, etc.).
So, we can see through the console the HTTP code for each resource.
Also, I find out that it is possible to validate some ajax call (done on page load) by using the resource.received event.
A+
Philip

### CODE REVIEW

**Comment by seethroughtrees** [comment]
Hi @doxakis thanks for this.  Can I give you collaborator access to the project?

**Comment by doxakis** [comment]
Hi,
Sure, you can add me.
Would you like to validate my code before it is merge on the master branch?
When I add new feature, I commit directly on the master branch ?
Thank

**Comment by seethroughtrees** [comment]
Hi Philip.  Just added you as a collaborator.  You can merge to master branch or any other.  Since the project is not on npm, all we have to do is just keep the master branch working as expected.

I've been extremely busy with other projects, so I'll check in when I can, but feel free to make any adjustments you think are necessary.

Thanks!

**Comment by seethroughtrees** [comment]
The change you made looks good to me, but I'm not able to test, so please test before merging!  Thanks.

**Pull request merged**
